config/routes.rb
Specscan::Application.routes.draw do

  devise_for :users, :skip => [:sessions] do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
      get 'impersonate', :on => :member
      get 'impersonation_logout', :on => :collection
      get 'update_balance', :on => :member
      post 'update_balance', :on => :member
    end
    resources :additional_users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
    end
    resources :vehicles do
      get 'map', :on => :member
      get 'overview_map', :on => :collection
      get 'reports', :on => :member
      get 'day_report', :on => :member
      get 'get_movement_points', :on => :member
      get 'get_last_point', :on => :member
      get 'calibration', :on => :member
      put 'calibration_save', :on => :member
      get 'clear', :on => :member
      put 'clear_do', :on => :member
      get 'waybill', :on => :member
    end
    resources :sim_cards do
      post 'check_balance', :on => :member
    end
    resources :fuel_sensors
    resources :drivers
    resources :plans
    match "profile" => "users#profile"
    match "tools(/:action)", :controller => 'tools'
    match "search" => "search#results"
  end

  namespace :api do
    resources :vehicles, :only => :index do
      get 'location', :on => :member
    end
  end

  root :to => 'admin/dashboard#index'

end

app/controllers/admin/additional_users_controller.rb
class Admin::AdditionalUsersController < Admin::Base

  before_filter :set_selected_user, :only => [:show, :edit, :update, :lock, :unlock, :destroy]

  def index
    @columns = %w{ login name email }
    @columns << 'owner_id' if can? :manage, :all
    @sort_state = get_list_sort_state(@columns, :additional_users_list, :dir => 'asc', :field => 'login')
    @users = User.page(get_list_page).
      where('role = ?', User::ROLE_USER).
      order("#{@sort_state[:field]} #{@sort_state[:dir]}")
    @users = @users.where('owner_id = ?', current_user.id) unless can? :manage, :all
  end

  def new
    @user = User.new(:role => User::ROLE_USER)
    @user.login = "#{@current_user.login}-user"
  end

  def create
    @user = User.new(params[:user])
    @user.role = User::ROLE_USER
    @user.owner = current_user unless can? :manage, :all

    if @user.save
      action_log(:create_additional_user, :user => @user.login, :owner => @user.owner.login)
      redirect_to(admin_additional_users_path, :notice => t('admin.additional_users.create.user_created', :login => @user.login))
    else
      render :action => 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    params[:user].delete(:login)
    params[:user].delete(:role)
    params[:user].delete(:owner_id) unless can? :manage, :all

    if @user.update_attributes(params[:user])
      action_log(:update_additional_user, :user => @user.login, :owner => @user.owner.login)
      redirect_to(admin_additional_users_path, :notice => t('admin.additional_users.update.user_updated', :login => @user.login))
    else
      render :action => 'edit'
    end
  end

  def lock
    @user.lock
    action_log(:lock_additional_user, :user => @user.login, :owner => @user.owner.login)
    redirect_to(admin_additional_user_path(@user), :notice => t('admin.additional_users.lock.locked', :login => @user.login))
  end

  def unlock
    @user.unlock
    action_log(:unlock_additional_user, :user => @user.login, :owner => @user.owner.login)
    redirect_to(admin_additional_user_path(@user), :notice => t('admin.additional_users.unlock.unlocked', :login => @user.login))
  end

  def destroy
    @user.destroy
    action_log(:destroy_additional_user, :user => @user.login, :owner => @user.owner.login)
    redirect_to(admin_additional_users_path, :notice => t('admin.additional_users.destroy.user_deleted'))
  end

  private

    def set_selected_user
      @user = User.find(params[:id])
      authorize! :edit, @user
    end

end

app/helpers/admin/additional_users_helper.rb
module Admin::AdditionalUsersHelper
end

app/views/admin/additional_users/_form.html.haml
= form_for([:admin_additional, @user], :html => { :class => 'form-horizontal' }) do |f|
  = render :partial => 'partials/form_errors', :locals => { :resource => @user, :locale_scope => 'admin.additional_users.form' }

  .control-group
    = f.label :login, t('.field.login'), :class => 'control-label'
    .controls
      - if @user.new_record?
        = f.text_field :login, :required => true
      - else
        %span.uneditable-input= @user.login

  - form_field f, :name, :text_field

  - if can? :manage, :all
    .control-group
      = f.label :user, t('.field.owner'), :class => 'control-label'
      .controls
        = select 'user', 'owner_id', User.clients.recently.collect { |user| [user.login, user.id] }

  - form_field f, :email, :email_field
  - form_field f, :password, :password_field
  - form_field f, :password_confirmation, :password_field
  - form_field f, :additional_info, :text_area, :rows => 2

  .form-actions
    = f.submit t('.button.' + (@user.new_record? ? 'create' : 'update')), :class => 'btn btn-primary'
    = link_to t('.button.back'), admin_additional_users_path, :class => 'btn'

app/views/admin/additional_users/edit.html.haml
- @page_title = t('.page_title', :login => @user.login)

= render 'form'

app/views/admin/additional_users/index.html.haml
- @page_title = t '.page_title'

- content_for :sidebar_actions do
  %li= link_to t('.action.add_user'), new_admin_additional_user_path

- if @users.empty?
  %p= t('.no_data')
- else
  = will_paginate @users

  %table.table.table-bordered.table-striped
    %thead
      %tr
        - @columns.each do |column_name|
          - if 'owner_id' == column_name
            %th= t(".column.owner")
          - else
            - sortable_column column_name, t(".column.#{column_name}"), @sort_state

    %tbody
      - @users.each do |user|
        %tr
          %td
            - if user.locked
              = image_tag "icons/lock.png", :class => 'inline-icon', :title => t('.hint.locked')
            = link_to user.login, admin_additional_user_path(user)
          %td= user.name
          %td= mail_to user.email
          - if can? :manage, :all
            %td= user.owner.login

  = will_paginate @users

app/views/admin/additional_users/new.html.haml
- @page_title = t '.page_title'
- @help = t '.help'

= render 'form'

app/views/admin/additional_users/show.html.haml
- @page_title = t '.page_title', :login => @user.login

%form.form-horizontal
  - %w{ login name email additional_info }.each do |field_name|
    - if !@user.send(field_name).blank?
      .control-group
        %label.control-label= t('admin.users.form.field.' + field_name)
        .control
          %span.uneditable-input= simple_format @user.send(field_name)

  .form-actions
    = link_to t('.button.back'), admin_additional_users_path, :class => 'btn btn-primary'
    = link_to t('.button.edit'), edit_admin_additional_user_path(@user), :class => 'btn'
    - if @user.unlocked
      = link_to t('.button.lock'), lock_admin_additional_user_path(@user), :class => 'btn btn-danger', :method => :post
    - else
      = link_to t('.button.unlock'), unlock_admin_additional_user_path(@user), :class => 'btn btn-success', :method => :post
    - if @user.deletable?
      = link_to t('.button.delete'), admin_additional_user_path(@user), :class => 'btn btn-danger', :method => :delete, 'data-confirm' => t('.button.confirm_delete')