config/routes.rb
Specscan::Application.routes.draw do

  devise_for :users, :skip => [:sessions] do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
      get 'impersonate', :on => :member
      get 'impersonation_logout', :on => :collection
      get 'update_balance', :on => :member
      post 'update_balance', :on => :member
    end
    resources :additional_users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
    end
    resources :vehicles do
      get 'map', :on => :member
      get 'overview_map', :on => :collection
      get 'reports', :on => :member
      get 'day_report', :on => :member
      get 'get_movement_points', :on => :member
      get 'get_last_point', :on => :member
      get 'calibration', :on => :member
      put 'calibration_save', :on => :member
      get 'clear', :on => :member
      put 'clear_do', :on => :member
      get 'waybill', :on => :member
    end
    resources :sim_cards do
      post 'check_balance', :on => :member
    end
    resources :fuel_sensors
    resources :drivers
    resources :plans
    match "profile" => "users#profile"
    match "tools(/:action)", :controller => 'tools'
    match "search" => "search#results"
  end

  namespace :api do
    resources :vehicles, :only => :index do
      get 'location', :on => :member
    end
  end

  root :to => 'admin/dashboard#index'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::Base

  def index
    redirect_to admin_vehicles_path unless current_user.admin?

    @clients_total = User.where(:role => User::ROLE_CLIENT).count if can? :manage, User
    @vehicles_total = can?(:manage, Vehicle) ? Vehicle.count(:all) : current_user.vehicles.count
    @plans_total = Plan.count(:all) if can? :manager, Plan
    @additional_users_total = User.where(:role => User::ROLE_USER).count if can? :manage, User
    @drivers_total = Driver.count(:all) if can? :manage, User
    @sim_cards_total = SimCard.count(:all) if can? :manage, SimCard
    @fuel_sensors_total = FuelSensor.count(:all) if can? :manage, FuelSensor

    @way_points_total = WayPoint.count
    @way_points_last_day = WayPoint.count(:timestamp => { '$gte' => (Time.now.to_i - 24.hours.to_i) })
    @movements_total = Movement.count
    @reports_total = Report.count
    @fuel_changes_total = FuelChange.count
    @activities_total = Activity.count
    @locations_total = Location.count

    @events = ActionLog.sort(:$natural.desc).limit(4).all
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.haml
- @page_title = t '.page_title'

%h3= t '.stats_title'

.row-fluid
  .span6
    %table.table.table-striped
      - if can? :manage, User
        %tr
          %th= link_to t('.stats.column.users'), admin_users_path
          %td= @clients_total
      %tr
        %th= link_to t('.stats.column.vehicles'), admin_vehicles_path
        %td= @vehicles_total
      %tr
        %th= link_to t('.stats.column.plans'), admin_plans_path
        %td= @plans_total
      %tr
        %th= link_to t('.stats.column.additional_users'), admin_additional_users_path
        %td= @additional_users_total
      %tr
        %th= link_to t('.stats.column.drivers'), admin_drivers_path
        %td= @drivers_total
      - if can? :manage, SimCard
        %tr
          %th= link_to t('.stats.column.sim_cards'), admin_sim_cards_path
          %td= @sim_cards_total
      - if can? :manage, FuelSensor
        %tr
          %th= link_to t('.stats.column.fuel_sensors'), admin_fuel_sensors_path
          %td= @fuel_sensors_total
  .span6
    %table.table.table-striped
      %tr
        %th= t('.stats.column.way_points')
        %td= number_with_delimiter(@way_points_total, :delimiter => ' ')
      %tr
        %th= t('.stats.column.way_points_last_day')
        %td= number_with_delimiter(@way_points_last_day, :delimiter => ' ')
      %tr
        %th= t('.stats.column.movements')
        %td= number_with_delimiter(@movements_total, :delimiter => ' ')
      %tr
        %th= t('.stats.column.reports')
        %td= number_with_delimiter(@reports_total, :delimiter => ' ')
      %tr
        %th= t('.stats.column.fuel_changes')
        %td= number_with_delimiter(@fuel_changes_total, :delimiter => ' ')
      %tr
        %th= t('.stats.column.activities')
        %td= number_with_delimiter(@activities_total, :delimiter => ' ')
      %tr
        %th= t('.stats.column.locations')
        %td= number_with_delimiter(@locations_total, :delimiter => ' ')

%h3= t '.action_log_title'

= render :partial => 'partials/action_logs_list', :locals => { :events => @events }