config/routes.rb
Specscan::Application.routes.draw do

  devise_for :users, :skip => [:sessions] do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
      get 'impersonate', :on => :member
      get 'impersonation_logout', :on => :collection
      get 'update_balance', :on => :member
      post 'update_balance', :on => :member
    end
    resources :additional_users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
    end
    resources :vehicles do
      get 'map', :on => :member
      get 'overview_map', :on => :collection
      get 'reports', :on => :member
      get 'day_report', :on => :member
      get 'get_movement_points', :on => :member
      get 'get_last_point', :on => :member
      get 'calibration', :on => :member
      put 'calibration_save', :on => :member
      get 'clear', :on => :member
      put 'clear_do', :on => :member
      get 'waybill', :on => :member
    end
    resources :sim_cards do
      post 'check_balance', :on => :member
    end
    resources :fuel_sensors
    resources :drivers
    resources :plans
    match "profile" => "users#profile"
    match "tools(/:action)", :controller => 'tools'
    match "search" => "search#results"
  end

  namespace :api do
    resources :vehicles, :only => :index do
      get 'location', :on => :member
    end
  end

  root :to => 'admin/dashboard#index'

end

app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base

  validates :code, :presence => true, :uniqueness => true, :format => { :with => /\A[a-z]+\z/ }
  validates :title, :presence => true, :uniqueness => true

end

app/controllers/admin/vehicles_controller.rb
class Admin::VehiclesController < Admin::Base

  before_filter :check_manage_permission, :only => [:new, :create, :destroy, :calibration, :calibration_save, :clear, :clear_do]
  before_filter :check_edit_permission, :only => [:edit, :update]
  before_filter :set_selected_vehicle, :only => [:show, :edit, :update, :map, :reports, :day_report, :destroy, :get_movement_points,
    :calibration, :calibration_save, :get_last_point, :clear, :clear_do, :waybill]

  def index
    @columns = %w{ name reg_number imei owner created_at }

    if can?(:manage, Vehicle) or (current_user.owner and current_user.owner.admin?)
      @sort_state = get_list_sort_state(@columns, :vehicles_admin_list, :dir => 'desc', :field => 'created_at')
      order = "#{@sort_state[:field]} #{@sort_state[:dir]}"
      @vehicles = Vehicle.page(params[:page]).joins(:user).select('vehicles.*, users.login as owner').order(order)
    else
      @sort_state = get_list_sort_state(@columns, :vehicles_list, :field => 'name')
      order = "#{@sort_state[:field]} #{@sort_state[:dir]}"
      user = current_user.user? ? current_user.owner : current_user
      @vehicles = user.vehicles.page(params[:page]).order(order)
    end
  end

  def show
  end

  def new
    user = params.key?(:user_id) ? User.find(params[:user_id]) : current_user
    generated_name = t('admin.vehicles.new.generated_name', :index => user.vehicles.count + 1)
    @vehicle = Vehicle.new(:user_id => user.id, :name => generated_name)
  end

  def create
    @vehicle = Vehicle.new(params[:vehicle])

    if @vehicle.save
      action_log(:create_vehicle, :vehicle => @vehicle.name, :user => @vehicle.user.login)
      redirect_to(admin_vehicles_path, :notice => t('admin.vehicles.create.vehicle_created'))
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    manager_only_fields = %w{ imei user_id tracker_model_id comment debt retranslate }
    manager_only_fields.each{ |field| params[:vehicle].delete(field.to_sym) } unless can? :manage, @vehicle

    if @vehicle.update_attributes(params[:vehicle])
      action_log(:update_vehicle, :vehicle => @vehicle.name)
      redirect_to(admin_vehicle_path(@vehicle), :notice => t('admin.vehicles.update.vehicle_updated'))
    else
      render :action => 'edit'
    end
  end

  def map
    time = params.key?(:date) ? Time.parse(params[:date]) : Date.today.to_time
    @selected_date = time.to_formatted_s(:date)
    @show_last_point = Date.today.to_time == time

    @movements = Movement.where(:imei => @vehicle.imei, :from_timestamp.gte => time.to_i, :from_timestamp.lt => time.to_i + 86400).
      sort(:from_timestamp)
    @last_point = WayPoint.where(:imei => @vehicle.imei, :coors_valid => true, :timestamp.lt => time.to_i + 86400).sort(:timestamp.desc).first

    @js_locale_keys = %w{ time speed }
  end

  def overview_map
    if can?(:manage, Vehicle) or (current_user.owner and current_user.owner.admin?)
      @vehicles = Vehicle.all(:order => 'name')
    else
      user = current_user.user? ? current_user.owner : current_user
      @vehicles = user.vehicles
    end
  end

  def get_movement_points
    movement = Movement.where(:imei => @vehicle.imei, '_id' => params[:movement_id]).first
    render :json => movement ? movement.get_points : []
  end

  def get_last_point
    @last_point = WayPoint.where(:imei => @vehicle.imei, :coors_valid => true).sort(:timestamp.desc).first
    render :json => { :latitude => @last_point.latitude, :longitude => @last_point.longitude }
  end

  def reports
    @months = []
    (0..2).each do |index|
      @months << {
        :name => t('month.name_' + (Date.today - index.month).month.to_s),
        :date => (Date.today - index.month).strftime('%Y.%m.01')
      }
    end

    month = (params.key?(:date) ? Date.parse(params[:date]) : Date.today).strftime('%Y%m')
    @selected_month = (params.key?(:date) ? Date.parse(params[:date]) : Date.today).strftime('%Y.%m.01')
    @reports = Report.where(:imei => @vehicle.imei, :date.gte => (month + '01').to_i, :date.lte => (month + '31').to_i).sort(:date.desc)
    @reports_summary = get_reports_summary(@reports, @vehicle)

    respond_to do |format|
      format.html
      format.xls if params[:format] == 'xls'
    end
  end

  def day_report
    time = params.key?(:date) ? Time.parse(params[:date]) : Date.today.to_time
    @selected_date = time.to_formatted_s(:date)
    @week_day = t('week_day.name_' + time.wday.to_s)
    @selected_date_last_minute = ((Time.now.to_i - time.to_i) < 86400 ? (Time.now.to_i - time.to_i) : 86400) / 60

    @movements = Movement.where(:imei => @vehicle.imei, :from_timestamp.gte => time.to_i, :from_timestamp.lt => time.to_i + 86400).
      sort(:from_timestamp)
    @movements_ranges = movements_ranges(@movements, time)
    @first_movement, @last_movement = get_boundary_movements(@movements)

    if @vehicle.has_activity_sensor?
      activities = Activity.where(:imei => @vehicle.imei, :from_timestamp.gte => time.to_i, :from_timestamp.lt => time.to_i + 86400).
        sort(:from_timestamp)
      @activities_ranges = activities_ranges(activities, time)
    end

    @report = Report.where(:imei => @vehicle.imei, :date => time.to_date.strftime('%Y%m%d').to_i).first
    @fuel_changes = FuelChange.where(:imei => @vehicle.imei, :from_timestamp.gte => time.to_i, :from_timestamp.lt => time.to_i + 86400).
      sort(:from_timestamp)
    @fuel_chart_data = get_fuel_details(time, @selected_date_last_minute)

    @js_locale_keys = %w{ parking_title movement_title activity_title reset_zoom reset_zoom_title }

    respond_to do |format|
      format.html
      format.xls if params[:format] == 'xls'
    end
  end

  def destroy
    @vehicle.destroy
    action_log(:destroy_vehicle, :vehicle => @vehicle.name)
    redirect_to(admin_vehicles_path, :notice => t('admin.vehicles.destroy.vehicle_deleted'))
  end

  def calibration
  end

  def calibration_save
    attributes = {
      :calibration_table => params[:vehicle][:calibration_table],
      :calibration_table2 => params[:vehicle][:calibration_table2],
    }

    if @vehicle.update_attributes(attributes)
      redirect_to(admin_vehicle_path(@vehicle), :notice => t('admin.vehicles.calibration_save.updated'))
    else
      render :action => 'calibration'
    end
  end

  def clear
  end

  def clear_do
    WayPoint.delete_all(:imei => @vehicle.imei) if params.key?(:way_points)
    Movement.delete_all(:imei => @vehicle.imei) if params.key?(:movements)
    Report.delete_all(:imei => @vehicle.imei) if params.key?(:reports)
    Activity.delete_all(:imei => @vehicle.imei) if params.key?(:activities)
    if params.key?(:fuel_changes)
      FuelChange.delete_all(:imei => @vehicle.imei)
      Movement.unset({ :imei => @vehicle.imei }, :fuel_last_update_timestamp)
      Movement.unset({ :imei => @vehicle.imei }, :fuel_used)
    end
    action_log(:clear_data_vehicle, :vehicle => @vehicle.name)
    redirect_to(admin_vehicle_path(@vehicle), :notice => t('admin.vehicles.clear_do.cleared'))
  end

  def waybill
    time = params.key?(:date) ? Time.parse(params[:date]) : Date.today.to_time
    @selected_date = time.to_formatted_s(:date)
    @waybill_types = get_waybill_types
    @drivers = @vehicle.user.drivers.collect{ |driver| [driver.name, driver.id] }
    @drivers = [[t('admin.vehicles.waybill.field.unknown_driver'), 0]] + @drivers
    @default_driver = @vehicle.drivers.first
    @selected_driver = params.key?(:driver) ? Driver.find_by_id(params[:driver]) : nil
    @selected_driver = nil if @selected_driver and @selected_driver.owner.id != @vehicle.user.id 

    respond_to do |format|
      format.html
      format.doc do
        waybill_file = 'car.xml'
        waybill_file = 'truck.xml' if 'truck' == params[:waybill_type]
        waybill_file = 'bus.xml' if 'bus' == params[:waybill_type]
        waybill_file = 'special.xml' if 'special' == params[:waybill_type]
        content = File.read(Rails.root.join('app', 'assets', 'files', 'waybills', waybill_file))
        content.gsub!('%org%', @vehicle.user.name)
        content.gsub!('%vehicle-name%', @vehicle.name)
        content.gsub!('%vehicle-reg-number%', @vehicle.reg_number)
        if @selected_driver
          content.gsub!('%driver-name%', @selected_driver.name)
          content.gsub!('%driver-license%', @selected_driver.license_number)
          content.gsub!('%driver-categories%', @selected_driver.categories)
        else
          content.gsub!('%driver-name%', '')
          content.gsub!('%driver-license%', '')
          content.gsub!('%driver-categories%', '')
        end
        render :text => content
      end
    end
  end

  private

    def check_manage_permission
      authorize! :manage, Vehicle
    end

    def check_edit_permission
      authorize! :edit, Vehicle
    end

    def set_selected_vehicle
      @vehicle = Vehicle.find(params[:id])
      authorize! :view, @vehicle
    end

    def get_boundary_movements(movements)
      movements = movements.find_all{ |movement| !movement.parking? }
      [nil, nil] if movements.blank?
      [movements.first, movements.last]
    end

    def movements_ranges(movements, day_start_time)
      ranges = []
      movements.each do |movement|
        from_time = (movement.from_time - day_start_time) / 60
        to_time = (movement.to_time - day_start_time) / 60
        ranges << [
          from_time.to_i,
          to_time.to_i,
          movement.parking? ? 0 : 1,
          movement.id
        ]
      end
      ranges
    end

    def activities_ranges(activities, day_start_time)
      ranges = []
      activities.each do |activity|
        from_time = (activity.from_time - day_start_time) / 60
        to_time = (activity.to_time - day_start_time) / 60
        ranges << [
          from_time.to_i,
          to_time.to_i,
          activity.active ? 1 : 0,
        ]
      end
      ranges
    end

    def get_reports_summary(reports, vehicle)

app/controllers/api/vehicles_controller.rb
class Api::VehiclesController < Api::Base

  before_filter :set_selected_vehicle, :only => [:location]

  def index
    owner = current_user.user? ? current_user.owner : current_user
    @vehicles = owner.vehicles
  end

  def location
    @point = @vehicle.last_point
  end

  private

    def set_selected_vehicle
      @vehicle = Vehicle.find(params[:id])
      authorize! :view, @vehicle
    end

end

app/helpers/admin/vehicles_helper.rb
module Admin::VehiclesHelper

  MIN_METERS_BETWEEN_POINTS = 10

  def timeframe(movement)
    "#{movement.from_time.to_formatted_s(:time)} - #{movement.to_time.to_formatted_s(:time)}"
  end

  def movement_info(movement, vehicle_id)
    first_point = get_point_by_timestamp(movement, movement.from_timestamp)
    second_point = get_point_by_timestamp(movement, movement.to_timestamp)

    {
      :vehicle_id => vehicle_id,
      :movement_id => movement.id,
      :title => t('.movement.' + (movement.parking ? 'parking_title' : 'movement_title')),
      :parking => movement.parking,
      :first_point => first_point,
      :last_point => second_point,
      :points => [],
      :from_time => t('.movement.from_time', :time => movement.from_time.to_formatted_s(:date_time)),
      :to_time => t('.movement.to_time', :time => movement.to_time.to_formatted_s(:date_time)),
      :duration => t('.movement.duration', :duration =>  duration_human(movement.elapsed_time)),
      :from_location => movement.from_location ? movement.from_location.address : '',
      :to_location => movement.to_location ? movement.to_location.address : '',
      :distance => movement.parking ? '' : t('.movement.distance', :distance => decimal_human(movement.distance_km)),
    }
  end

  def movement_fuel_used(movement)
    return 0 if movement.fuel_used.to_i < FuelChange::FUEL_TRESHOLD_LITRES
    decimal_human(movement.fuel_used)
  end

  def last_point_info(way_point, title, link = nil)
    {
      :title => title,
      :description => t('.last_point.time', :time => way_point.time.to_formatted_s(:date_time)),
      :latitude => way_point.latitude,
      :longitude => way_point.longitude,
      :link => link ? link : ''
    }
  end

  def tracker_models_list
    list = TrackerModel.all.collect { |model| [model.title, model.id] }
    [[t('admin.vehicles.form.field.unknown_tracker'), 0]] + list
  end

  def duration_human(duration)
    duration = 0 if duration.blank?
    seconds = duration % 60
    minutes = duration / 60
    hours = minutes / 60
    minutes = minutes % 60
    "%d:%.2d" % [hours, minutes]
  end

  def decimal_human(decimal)
    return 0 if decimal.blank?
    "%.1f" % decimal
  end

  def get_point_by_timestamp(movement, timestamp)
    point = WayPoint.where(:imei => movement.imei, :coors_valid => true, :timestamp.lte => timestamp).sort(:timestamp.desc).first
    result = {}
    %w{ latitude longitude }.each{ |name| result[name] = point.send(name)  }
    result
  end

  def get_point_address(way_point)
    location = Location.where({ :coors => { '$near' => [way_point['latitude'], way_point['longitude']] } }).first
    return '' unless location
    return '' if (location.coors.first - way_point['latitude']).abs > 0.01 or (location.coors.last - way_point['longitude']).abs > 0.01
    location.address
  end

end

app/helpers/api/vehicles_helper.rb
module Api::VehiclesHelper
end

app/views/admin/vehicles/day_report.html.haml
- @page_title = t '.page_title', :vehicle_title => @vehicle.title

= javascript_include_tag "external/highcharts"
= javascript_include_tag "external/jquery-tablesorter-min"
= javascript_tag "movementRanges = #{@movements_ranges.to_json}"
= javascript_tag "activityRanges = #{@activities_ranges ? @activities_ranges.to_json : '[]'}"
= javascript_tag "selectedDateLastMinute = #{@selected_date_last_minute}"
= javascript_tag "jsLocaleKeys = #{Hash[*@js_locale_keys.collect{ |key| [key, t('.' + key)] }.flatten].to_json}"
= javascript_tag "fuelChartData = #{@vehicle.fuel_sensor ? @fuel_chart_data.to_json : '[]'}"
= javascript_tag "tankSize = #{@vehicle.fuel_sensor ? @vehicle.fuel_tank.to_i : 0}"

- content_for :sidebar_actions do
  %li= link_to t('.action.map'), map_admin_vehicle_path(:date => @selected_date)
  %li= link_to t('.action.reports'), reports_admin_vehicle_path
  %li= link_to t('.action.details'), admin_vehicle_path
  %li= link_to t('.action.download'), day_report_admin_vehicle_path(:format => :xls, :date => @selected_date)
  %li= link_to t('.action.waybill'), waybill_admin_vehicle_path(:date => @selected_date) 

- content_for :sidebar do
  %h4= t '.date_picker'
  %ul
    %li= link_to @selected_date, '#', :id => 'selectedDate', 'data-datepicker' => 'datepicker'

- if @movements.blank? and @fuel_changes.blank?
  %p= t('.no_data')
- else

  - if @report
    %h3= t '.header.stats'
  %table.table.table-bordered.table-striped
    %tr
      %th{ :width => '35%' }= t '.stats.date'
      %td{ :width => '15%' }= @selected_date
      %th{ :width => '35%' }= t '.stats.week_day'
      %td{ :width => '15%' }= @week_day
    - if @report
      %tr
        %th= t '.stats.movements'
        %td= @report.movement_count
        %th= t '.stats.movements_duration'
        %td= duration_human(@report.movement_time)
      %tr
        %th= t '.stats.parking'
        %td= @report.parking_count
        %th= t '.stats.parking_duration'
        %td= duration_human(@report.parking_time)
      - if @report.movement_count > 0
        %tr
          %th= t '.stats.first_movement_start'
          %td= @first_movement.from_time.to_formatted_s(:date_time)
          %th= t '.stats.last_movement_end'
          %td= @last_movement.to_time.to_formatted_s(:date_time)
      - if @movements.count > 0 and @vehicle.has_fuel_analytics?
        %tr
          %th= t '.stats.fuel_on_start'
          %td= @vehicle.fuel_by_time(@movements.first.from_timestamp).floor
          %th= t '.stats.fuel_on_end'
          %td= @vehicle.fuel_by_time(@movements.last.to_timestamp).floor
      %tr
        %th= t '.stats.distance'
        %td= (@report.distance.to_f / 1000).round
        %th= t '.stats.fuel'
        %td= (Vehicle::FUEL_CALC_BY_MHOURS == @vehicle.fuel_calc_method ? @report.fuel_norm.to_f : (@report.fuel_norm.to_f / 1000)).round
      - if @vehicle.has_fuel_analytics?
        %tr
          %th= t '.stats.refuels'
          %td= (@report.fuel_added.to_f).round.to_s + ' / ' + (@report.fuel_stolen.to_f).round.to_s
          %th= t '.stats.fuel_used'
          %td= (@report.fuel_used > 0 ? @report.fuel_used : 0).round
      - if Vehicle::FUEL_CALC_BY_MHOURS == @vehicle.fuel_calc_method
        %tr
          %th= t '.stats.active_duration'
          %td= duration_human(@report.active_time)
          %th= t '.stats.static_work_duration'
          %td= duration_human(@report.static_work_time)

  %h3= t '.header.chart'
  #movementsChart{ :style => 'width: 100%; height: 100px;' }

  - if @vehicle.fuel_sensor and @vehicle.fuel_tank.to_i > 0
    %h3= t '.header.fuel_chart'
    #fuelChangesChart{ :style => 'width: 100%; height: 200px;' }

    - if @vehicle.has_fuel_analytics?
      %h3= t '.header.fuel_changes_list'

      - if @fuel_changes.blank?
        %p= t('.no_data')
      - else
        %table.table.table-bordered.table-striped
          %thead
            %tr
            - %w{ type from_time to_time duration amount }.each do |column_name|
              %th= t ".column_fuel.#{column_name}"

          %tbody
            - @fuel_changes.each do |fuel_change|
              %tr
                %td
                  = image_tag "icons/#{fuel_change.refuel? ? 'plus-circle' : 'minus-circle'}.png", :class => 'inline-icon'
                  = t('.' + (fuel_change.refuel? ? 'refuel_title' : 'fuel_theft_title'))
                %td= fuel_change.from_time.to_formatted_s(:date_time)
                %td= fuel_change.to_time.to_formatted_s(:date_time)
                %td= duration_human(fuel_change.elapsed_time)
                %td= fuel_change.amount.round

  %h3= t '.header.movements_list'
  %table#movements-list.table.table.table-bordered.table-striped.tablesorter
    %thead
      %tr
        - %w{ type from_time to_time duration distance }.each do |column_name|
          %th= link_to t(".column.#{column_name}"), '#'
        - if @vehicle.has_fuel_analytics?
          %th= link_to t('.column.fuel_used'), '#'

    %tbody
      - @movements.each do |movement|
        %tr
          %td{ :width => 120 }
            = image_tag "icons/#{movement.parking ? 'parking' : 'arrow_down'}.png", :class => 'inline-icon'
            = link_to t('.' + (movement.parking ? 'parking_title' : 'movement_title')), map_admin_vehicle_path(:date => @selected_date, :anchor => movement._id)
          %td
            %span.hide>= movement.from_time.to_i
            = movement.from_time.to_formatted_s(:date_time)
            - if movement.from_location
              %br
              %span{ :rel => 'tooltip', :title => movement.from_location.details }= movement.from_location.address
          %td
            = movement.to_time.to_formatted_s(:date_time)
            - if movement.to_location
              %br
              - unless movement.parking
                %span{ :rel => 'tooltip', :title => movement.to_location.details }= movement.to_location.address
              - else
                = raw("&mdash;")
          %td{ :width => 185 }= duration_human(movement.elapsed_time)
          %td{ :width => 80 }= movement.parking ? raw('&mdash;') : decimal_human(movement.distance_km)
          - if @vehicle.has_fuel_analytics?
            %td= (0 == movement_fuel_used(movement)) ? raw('&mdash;') : movement_fuel_used(movement)

app/views/admin/vehicles/edit.html.haml
- @page_title = t '.page_title', :vehicle_title => @vehicle.title

= render 'form'

app/views/admin/vehicles/index.html.haml
- @page_title = t '.page_title'

- content_for :sidebar_actions do
  - if can? :manage, Vehicle
    %li= link_to t('.action.add_vehicle'), new_admin_vehicle_path
  %li= link_to t('.action.overview_map'), overview_map_admin_vehicles_path

= will_paginate @vehicles

= render :partial => 'partials/vehicles_list', :locals => { :vehicles => @vehicles, :sort_state => @sort_state }

= will_paginate @vehicles

app/views/admin/vehicles/new.html.haml
- @page_title = t '.page_title'

= render 'form'

app/views/admin/vehicles/show.html.haml
- @page_title = t '.page_title', :vehicle_title => @vehicle.title

- content_for :sidebar_actions do
  %li= link_to t('.action.reports'), reports_admin_vehicle_path(@vehicle)
  %li= link_to t('.action.map'), map_admin_vehicle_path(@vehicle)
  - if can? :manage, @vehicle
    %li= link_to t('.action.calibration'), calibration_admin_vehicle_path(@vehicle)

%form.form-horizontal
  - %w{ name vehicle_type tracker_name imei fuel_sensor reg_number distance_multiplier fuel_norm fuel_tank fuel_tank2 drivers }.each do |field_name|
    - next if %w{ imei tracker_name fuel_sensor }.include?(field_name) and !can?(:manage, @vehicle)
    - if !@vehicle.send(field_name).blank?
      .control-group
        %label.control-label= t('admin.vehicles.form.field.' + field_name)
        .controls
          %span.uneditable-input
            - if 'fuel_sensor' == field_name
              - if can?(:manage, @vehicle)
                = link_to "#{@vehicle.fuel_sensor.code} (#{@vehicle.fuel_sensor.fuel_sensor_model.title})", admin_fuel_sensor_path(@vehicle.fuel_sensor)
              - else
                = @vehicle.fuel_sensor.fuel_sensor_model.title
            - elsif 'imei' == field_name
              = link_to(image_tag('icons/application-monitor.png'), { :controller => 'admin/tools', :action => 'packets_monitor', :imei => @vehicle.imei })
              = @vehicle.imei
            - elsif 'vehicle_type' == field_name
              = @vehicle.vehicle_type.title
            - elsif 'drivers' == field_name
              = @vehicle.drivers.collect{ |driver| driver.name }.join(', ')
            - else
              = @vehicle.send(field_name)

  - readonly_field(t('admin.vehicles.form.field.min_parking_time'), @vehicle.min_parking_time) if can?(:manage, @vehicle) and !@vehicle.min_parking_time.blank?
  - if can?(:manage, @vehicle) and @vehicle.sim_card
    - readonly_field(t('admin.vehicles.form.field.sim_card'), link_to(number_to_phone(@vehicle.sim_card.phone), admin_sim_card_path(@vehicle.sim_card)))
  - readonly_field(t('admin.vehicles.form.field.user'), link_to(@vehicle.user.login, admin_user_path(@vehicle.user))) if can? :manage, @vehicle
  - readonly_field(t('admin.vehicles.form.field.description'), simple_format(@vehicle.description)) if !@vehicle.description.blank?
  - readonly_field(t('admin.vehicles.form.field.comment'), simple_format(@vehicle.comment)) if can?(:manage, @vehicle) and !@vehicle.comment.blank?
  - readonly_field(t('admin.vehicles.form.field.debt'), @vehicle.debt) if can?(:manage, @vehicle) and !@vehicle.debt.zero?
  - readonly_field(t('admin.vehicles.form.field.retranslate'), @vehicle.retranslate) if can?(:manage, @vehicle) and @vehicle.retranslate

  .form-actions
    - if can? :edit, @vehicle
      = link_to t('.button.edit'), edit_admin_vehicle_path(@vehicle), :class => 'btn btn-primary'
    = link_to t('.button.back'), admin_vehicles_path, :class => 'btn'
    - if can? :destroy, @vehicle
      = link_to t('.button.clear_data'), clear_admin_vehicle_path(@vehicle), :class => 'btn'
      = link_to t('.button.delete'), admin_vehicle_path(@vehicle), :class => 'btn btn-danger', :method => :delete, 'data-confirm' => t('.button.confirm_delete')

app/views/admin/vehicles/waybill.html.haml
- @page_title = t '.page_title', :vehicle_title => @vehicle.title

- content_for :sidebar_actions do
  %li= link_to t('.action.day_report'), day_report_admin_vehicle_path(:date => @selected_date)

- content_for :sidebar do
  %h4= t '.date_picker'
  %ul
    %li= link_to @selected_date, '#', :id => 'selectedDate', 'data-datepicker' => 'datepicker'

= form_for([:admin, @vehicle], :url => waybill_admin_vehicle_path(:format => :doc, :date => @selected_date), :method => 'get', :html => { :class => 'form-horizontal' }) do |f|
  = render :partial => 'partials/form_errors', :locals => { :resource => @vehicle, :locale_scope => 'admin.vehicles.waybill' }

  - readonly_field(t('.field.name'), @vehicle.name)
  - readonly_field(t('.field.reg_number'), @vehicle.reg_number)

  .control-group
    = f.label :waybill_type, t('.field.waybill_type'), :class => 'control-label'
    .controls
      = select_tag(:waybill_type, options_for_select(@waybill_types.collect { |type| [type[:title], type[:name]] }, @vehicle.waybill_type))

  .control-group
    = f.label :driver, t('.field.driver'), :class => 'control-label'
    .controls
      = select_tag(:driver, options_for_select(@drivers, @default_driver ? @default_driver.id : 0))

  .form-actions
    = f.submit t('.button.download'), :class => 'btn btn-primary'
    = link_to t('.button.back'), admin_vehicle_path(@vehicle), :class => 'btn'