config/routes.rb
Specscan::Application.routes.draw do

  devise_for :users, :skip => [:sessions] do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
      get 'impersonate', :on => :member
      get 'impersonation_logout', :on => :collection
      get 'update_balance', :on => :member
      post 'update_balance', :on => :member
    end
    resources :additional_users do
      post 'lock', :on => :member
      post 'unlock', :on => :member
    end
    resources :vehicles do
      get 'map', :on => :member
      get 'overview_map', :on => :collection
      get 'reports', :on => :member
      get 'day_report', :on => :member
      get 'get_movement_points', :on => :member
      get 'get_last_point', :on => :member
      get 'calibration', :on => :member
      put 'calibration_save', :on => :member
      get 'clear', :on => :member
      put 'clear_do', :on => :member
      get 'waybill', :on => :member
    end
    resources :sim_cards do
      post 'check_balance', :on => :member
    end
    resources :fuel_sensors
    resources :drivers
    resources :plans
    match "profile" => "users#profile"
    match "tools(/:action)", :controller => 'tools'
    match "search" => "search#results"
  end

  namespace :api do
    resources :vehicles, :only => :index do
      get 'location', :on => :member
    end
  end

  root :to => 'admin/dashboard#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  ROLE_ADMIN = 1
  ROLE_CLIENT = 2
  ROLE_USER = 3
  ROLES = [['admin', ROLE_ADMIN], ['client', ROLE_CLIENT], ['user', ROLE_USER]]

  validates :login, :presence => true, :uniqueness => true, :length => { :minimum => 3, :maximum => 20 },
    :format => { :with => /^[-a-z\d]+$/ }
  validates :password, :presence => true, :confirmation => true, :on => :create,
    :length => { :minimum => 6, :maximum => 25 }, :format => { :with => /^[a-zA-Z\d]+$/ }
  validates :role, :presence => true
  validates :balance, :numericality => true
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  attr_accessible :login, :name, :email, :password, :password_confirmation, :remember_me, :role, :contact_name,
    :phone, :additional_info, :comment, :owner_id, :balance

  has_many :vehicles, :order => 'name'
  belongs_to :owner, :class_name => 'User', :foreign_key => 'owner_id'
  has_many :additional_users, :class_name => 'User', :foreign_key => 'owner_id', :dependent => :destroy
  has_many :drivers, :foreign_key => 'owner_id', :dependent => :destroy

  scope :clients, where('role IN (?)', [User::ROLE_CLIENT, User::ROLE_ADMIN]).order('login') 
  scope :recently, order('created_at DESC')

  def admin?
    ROLE_ADMIN == role
  end

  def client?
    ROLE_CLIENT == role
  end

  def user?
    ROLE_USER == role
  end

  def role_name
    case role
      when ROLE_ADMIN then 'admin'
      when ROLE_CLIENT then 'client'
      when ROLE_USER then 'user'
    end
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def lock
    self.locked = true
    save
  end

  def unlock
    self.locked = false
    save
  end

  def unlocked
    !locked
  end

  def active_for_authentication?
    super && unlocked && (owner ? owner.unlocked : true)
  end

  def deletable?
    user? or 0 == vehicles.count
  end

  def self.authenticate(login, password)
    user = self.find_by_login(login)
    return false unless user
    return false unless user.valid_password?(password)
    user
  end

  protected

    def email_required?
      false
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base

  before_filter :check_manage_permission, :except => [:profile, :update, :destroy, :impersonate, :impersonation_logout]
  before_filter :set_selected_user, :only => [:show, :edit, :update, :lock, :unlock, :destroy, :impersonate, :update_balance]

  def index
    @columns = %w{ login name balance vehicles_total created_at }
    @sort_state = get_list_sort_state(@columns, :users_list, :dir => 'desc', :field => 'created_at')
    @users = User.page(get_list_page).
      joins("LEFT JOIN vehicles ON users.id = vehicles.user_id").
      select("users.*, COUNT(vehicles.user_id) AS vehicles_total").
      where('role IN (?)', [User::ROLE_CLIENT, User::ROLE_ADMIN]).
      group("users.id").
      order("#{@sort_state[:field]} #{@sort_state[:dir]}")
  end

  def new
    @user = User.new(:role => User::ROLE_CLIENT)
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      action_log(:create_user, :login => @user.login)
      redirect_to(admin_users_path, :notice => t('admin.users.create.user_created', :login => @user.login))
    else
      render :action => 'new'
    end
  end

  def show
    @columns = %w{ name reg_number imei owner created_at }
    @sort_state = get_list_sort_state(@columns, :user_vehicles_admin_list, :dir => 'desc', :field => 'created_at')
    order = "#{@sort_state[:field]} #{@sort_state[:dir]}"
    @vehicles = @user.vehicles.reorder(order) if @user.vehicles.length > 0
  end

  def edit
  end

  def profile
    @user = current_user
    @profile = true
  end

  def update
    authorize! :manage, User if @user.id != current_user.id

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    params[:user].delete(:login)
    params[:user].delete(:role) unless can? :manage, @user

    if @user.update_attributes(params[:user])
      action_log(:update_user, :login => @user.login)
      if params.key?(:profile)
        redirect_to(admin_profile_path, :notice => t('admin.profile.updated'))
      else
        redirect_to(admin_users_path, :notice => t('admin.users.update.user_updated', :login => @user.login))
      end
    else
      render :action => 'edit'
    end
  end

  def lock
    @user.lock
    action_log(:lock_user, :login => @user.login)
    redirect_to(admin_user_path(@user), :notice => t('admin.users.lock.locked', :login => @user.login))
  end

  def unlock
    @user.unlock
    action_log(:unlock_user, :login => @user.login)
    redirect_to(admin_user_path(@user), :notice => t('admin.users.unlock.unlocked', :login => @user.login))
  end

  def destroy
    @user.destroy
    action_log(:destroy_user, :login => @user.login)
    redirect_to(admin_users_path, :notice => t('admin.users.destroy.user_deleted'))
  end

  def impersonate
    redirect_to(root_path) unless session[:impersonated_user_id] or authorize! :manage, User
    session[:impersonated_user_id] = current_user.id unless session[:impersonated_user_id]
    relogin(@user)
  end

  def impersonation_logout
    user = User.find(session[:impersonated_user_id])
    session.delete(:impersonated_user_id)
    relogin(user)
  end

  def update_balance
    if request.post?
      amount = params[:amount].to_i
      @user.balance += amount
      @user.save
      action_log(:update_balance, :login => @user.login, :amount => amount)
      redirect_to(admin_user_path(@user), :notice => t('admin.users.update_balance.updated', :login => @user.login, :amount => amount))
    end
  end

  private

    def check_manage_permission
      authorize! :manage, User
    end

    def set_selected_user
      @user = User.find(params[:id])
    end

    def relogin(user)
      sign_out :user
      sign_in user
      redirect_to root_path
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for([:admin, @user], :html => { :class => 'form-horizontal' }) do |f|
  = render :partial => 'partials/form_errors', :locals => { :resource => @user, :locale_scope => 'admin.users.form' }

  .control-group
    = f.label :login, t('.field.login'), :class => 'control-label'
    .controls
      - if @user.new_record?
        = f.text_field :login, :required => true, :autofocus => true
      - else
        %span.uneditable-input= @user.login

  - form_field f, :name, :text_field
  - form_field f, :email, :email_field
  - form_field f, :password, :password_field
  - form_field f, :password_confirmation, :password_field

  - unless @profile
    .control-group
      = f.label :role, t('.field.role'), :class => 'control-label'
      .controls
        = f.select :role, options_for_select([[t('.field.role_client'), User::ROLE_CLIENT], [t('.field.role_admin'), User::ROLE_ADMIN]], { :selected => @user.role || User::ROLE_CLIENT })

  - if @profile
    = hidden_field_tag :profile, true

  - unless @user.user?
    - form_field f, :contact_name, :text_field
    - form_field f, :phone, :text_field

  - form_field f, :additional_info, :text_area, :rows => 2
  - if can? :manage, @user
    - form_field f, :comment, :text_area, :rows => 2

  .form-actions
    = f.submit t('.button.' + (@user.new_record? ? 'create' : 'update')), :class => 'btn btn-primary'
    - if !@profile
      = link_to t('.button.back'), admin_users_path, :class => 'btn'

app/views/admin/users/index.html.haml
- @page_title = t '.page_title'

- content_for :sidebar_actions do
  %li= link_to t('.action.add_user'), new_admin_user_path
  %li= link_to t('.action.additional_users'), admin_additional_users_path
  %li= link_to t('.action.drivers'), admin_drivers_path

= will_paginate @users

%table.table.table-bordered.table-striped
  %thead
    %tr
      - @columns.each do |column_name|
        - sortable_column column_name, t(".column.#{column_name}"), @sort_state
      %th= t '.column.impersonation'

  %tbody
    - @users.each do |user|
      %tr
        %td
          - if user.locked
            = image_tag "icons/lock.png", :class => 'inline-icon', :title => t('.hint.locked')
          - if user.admin?
            = image_tag "icons/star.png", :class => 'inline-icon', :title => t('.hint.admin')
          = link_to user.login, admin_user_path(user)
        %td= user.name
        %td= user.balance
        %td= user.vehicles.count
        %td= l user.created_at.localtime
        %td
          - if user.admin?
            &mdash;
          - else
            = image_tag "icons/door_in.png", :class => 'inline-icon'
            = link_to(t('.action.impersonation'), impersonate_admin_user_path(user))

= will_paginate @users

app/views/admin/users/profile.html.haml
- @page_title = t('admin.profile.page_title')
- @help = t('admin.profile.help')

= render 'form'

app/views/admin/users/show.html.haml
- @page_title = t '.page_title', :login => @user.login

- content_for :sidebar_actions do
  - if can? :manage, Vehicle
    %li= link_to t('.action.add_vehicle'), new_admin_vehicle_path(:user_id => @user)
    %li= link_to t('.action.update_balance'), update_balance_admin_user_path(:user_id => @user)

%form.form-horizontal
  - %w{ login name balance email role contact_name phone additional_info comment created_at updated_at }.each do |field_name|
    - if %w{ role created_at updated_at }.include?(field_name) or !@user.send(field_name).blank?
      .control-group
        %label.control-label= t('admin.users.form.field.' + field_name)
        .control
          - if 'role' == field_name
            %span.uneditable-input= t('admin.users.form.field.role_' + @user.send(field_name + '_name'))
          - elsif 'email' == field_name
            %span.uneditable-input= mail_to @user.email
          - elsif 'balance' == field_name
            %span.uneditable-input= @user.balance
          - elsif %w{ created_at updated_at }.include? field_name
            %span.uneditable-input= l @user.send(field_name).localtime
          - else
            %span.uneditable-input= simple_format @user.send(field_name)

  .form-actions
    = link_to t('.button.back'), admin_users_path, :class => 'btn btn-primary'
    = link_to t('.button.edit'), edit_admin_user_path(@user), :class => 'btn'
    - if @user.unlocked
      = link_to t('.button.lock'), lock_admin_user_path(@user), :class => 'btn btn-danger', :method => :post
    - else
      = link_to t('.button.unlock'), unlock_admin_user_path(@user), :class => 'btn btn-success', :method => :post
    - if @user.deletable?
      = link_to t('.button.delete'), admin_user_path(@user), :class => 'btn btn-danger', :method => :delete, 'data-confirm' => t('.button.confirm_delete')

- if can?(:manage, Vehicle) and @user.vehicles.length > 0
  %h2= t('.vehicles.title')

  = render :partial => 'partials/vehicles_list', :locals => { :vehicles => @vehicles, :sort_state => @sort_state }

app/views/admin/users/update_balance.html.haml
- @page_title = t '.page_title', :login => @user.login

= form_for([:admin, @user], :url => update_balance_admin_user_path(@user), :method => 'post', :html => { :class => 'form-horizontal' }) do |f|

  - %w{ login name balance }.each do |field_name|
    .control-group
      %label.control-label= t('admin.users.form.field.' + field_name)
      .controls
        %span.uneditable-input= @user.send(field_name)

  .control-group
    %label.control-label= t('.form.field.amount')
    .controls
      = text_field_tag 'amount'

  .form-actions
    = f.submit t('.button.update'), :class => 'btn btn-primary'
    = link_to t('.button.back'), admin_user_path(@user), :class => 'btn'